# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
#  url = "#about"
#   url = "#title_page"
#   url = "#slider"
#   url = "#title_page2"
 url = "#homepage"
weight = 100

[[main]]
  name = "People"
  url = "#people"
  weight = 200
  
[[main]]
  name = "Research"
  url = "#projects"
  weight = 300
  hasChildren = true
  identifier = "current_projects"
 
[[main]]
  name = "Biophysics & Soft Matter Physics"
  url = "#projects"
  weight = "10"
  parent = "current_projects"
  hasChildren = true
  identifier = "current_projects_biosoftmatter"


[[main]]
  name = "Condensed Matter Physics"
  url = "#projects"
  weight = "20"
  parent = "current_projects"
  hasChildren = true
  identifier = "current_projects_condensedmatter"

  
[[main]]
  name = "Theoretical Physics"
  url = "#projects"
  weight = "30"
  parent = "current_projects"
  hasChildren = true
  identifier = "current_projects_theoreticalphysics"  
  
#[[main]]
#  name = "Membrane Proteins Structure and Function"
##  url = "project/biophysics/membrane_protein/"
##  url = "#projects_biophysics"
#  url = "#projects"
#  weight = "1"
#  parent = "current_projects_biosoftmatter"
##  hasChildren = false

#[[main]]
#  name = "Functional and Mechanical Properties of Biological Soft Matter"
##  url = "project/biophysics/bio_soft_matter/"
##  url = "#projects_biophysics"
#  url = "#projects"  
#  weight = "2"
#  parent = "current_projects_biosoftmatter"
  
#[[main]]
#  name = "Cell-Penetrating Peptides(CPPs) and Drug Delivery"
##  url = "project/biophysics/cpp/"
##  url = "#projects_biophysics"
#  url = "#projects"
#  weight = "3"
#  parent = "current_projects_biosoftmatter" 
  
#[[main]]
#  name = "Path Sampling of Rare Events"
##  url = "project/biophysics/path_sampling/"
##  url = "#projects_biophysics"
#  url = "#projects"
#  weight = "4"
#  parent = "current_projects_biosoftmatter" 

#[[main]]
#  name = "Theoretical Modeling of a Cell Division and the Min System"
##  url = "project/biophysics/cell_division/"
##  url = "#projects_biophysics"
#  url = "#projects"
#  weight = "5"
#  parent = "current_projects_biosoftmatter"


#[[main]]
#  name = "Light-harvesting: Mechanisms of Energy Transfer"
##  url = "project/biophysics/cell_division/"
##  url = "#projects_biophysics"
#  url = "#projects"
#  weight = "6"
#  parent = "current_projects_biosoftmatter"
  

#[[main]]
#  name = "Self-Assembly of Polymers"
###  url = "project/soft_matter_physics/self_assembly/"
##  url = "#projects_softmatter"
#  url = "#projects"
#  weight = "7"
#  parent = "current_projects_biosoftmatter"


#[[main]]
#  name = "Polyelectrolyte-Polyampholyte Complexes"
###  url = "project/soft_matter_physics/pe_pa/"
##  url = "#projects_softmatter"
#  url = "#projects"
#  weight = "8"
#  parent = "current_projects_biosoftmatter"

#[[main]]
#  name = "Ion Transport in Water-in-salt Electrolytes(WISEs)"
###  url = "project/soft_matter_physics/WISE/"
##  url = "#projects_softmatter"
#  url = "#projects"
#  weight = "9"
#  parent = "current_projects_condensedmatter"
  
  
[[main]]
  name = "Publications"
  url = "#featured"
  weight = 400
  hasChildren = true
  identifier = "recent_publications"

  
[[main]]
  name = "Gallery"
#  url = "#gallery"
   url = "#featured"
  weight = "450"
  parent = "selected_publications"
#  hasChildren = true
  identifier = "selected_publications_gallery"


  
[[main]]
  name = "News"
  url = "#posts"
#  url = "#post2"
  weight = 600

[[main]]
  name = "Photos"
  url = "#talks"
  weight = 700

[[main]]
  name = "Open Positions"
  url = "#positions"
  weight = 800
  
[[main]]
  name = "Contact"
  url = "#contact"
  weight = 900



# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
