# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
#   url = "#title_page"
#   url = "#slider"
#   url = "#title_page2"
weight = 10

[[main]]
  name = "Team Members"
  url = "#people"
  weight = 20
  
[[main]]
  name = "Research"
  url = "#projects"
  weight = 30
  hasChildren = true
  identifier = "current_projects"
 
[[main]]
  name = "Overview"
  url = "#projects"
  weight = "1"
  parent = "current_projects"
  
[[main]]
  name = "Membrane Proteins Structure and Function"
  url = "project/membrane_protein/"
  weight = "2"
  parent = "current_projects"
  
[[main]]
  name = "Functional and Mechanical Properties of Biological Soft Matter"
  url = "project/soft_matter/"
  weight = "3"
  parent = "current_projects"
  
[[main]]
  name = "Cell-Penetrating Peptides(CPPs) and Drug Delivery"
  url = "project/cpp/"
  weight = "4"
  parent = "current_projects" 
  
[[main]]
  name = "Path Sampling of Rare Events"
  url = "project/path_sampling/"
  weight = "5"
  parent = "current_projects" 

[[main]]
  name = "Theoretical Modeling of a Cell Division and the MinSystem"
  url = "project/cell_division/"
  weight = "6"
  parent = "current_projects"
  


[[main]]
  name = "Publications"
  url = "#featured"
  weight = 40
  
[[main]]
  name = "Posts"
  url = "#posts"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
