# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Team Members"
  url = "#people"
  weight = 20
  
[[main]]
  name = "Research Projects"
  url = "#projects"
  weight = 30
  hasChildren = true
  identifier = "current_projects"
  
[[main]]
  name = "membrane protein structure and function"
  url = "project/membrane_protein/"
  weight = "1"
  parent = "current_projects"
  
[[main]]
  name = "functional and mechanical properties of biological soft matter"
  url = "project/soft_matter/"
  weight = "2"
  parent = "current_projects"
  
[[main]]
  name = "cell-penetrating peptides(CPPs) and drug delivery"
  url = "project/cpp/"
  weight = "3"
  parent = "current_projects" 
  
[[main]]
  name = "path sampling of rare events"
  url = "project/path_sampling/"
  weight = "4"
  parent = "current_projects" 

[[main]]
  name = "theoretical modeling of a cell devision and the min system"
  url = "project/cell_devision/"
  weight = "5"
  parent = "current_projects"
  


[[main]]
  name = "Publications"
  url = "#featured"
  weight = 40
  
[[main]]
  name = "Posts"
  url = "#posts"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
