# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
#  url = "#about"
#   url = "#title_page"
#   url = "#slider"
#   url = "#title_page2"
 url = "#homepage"
weight = 100

[[main]]
  name = "People"
  url = "#people"
  weight = 200
  
[[main]]
  name = "Research"
  url = "#projects"
  weight = 300
  hasChildren = true
  identifier = "current_projects"
 
[[main]]
  name = "Biophysics"
  url = "#projects_biophysics"
  weight = "10"
  hasChildren = true
  parent = "current_projects"
  identifier = "current_projects_biophysics"


[[main]]
  name = "Soft Matter Physics"
  url = "#projects_softmatter"
  weight = "20"
  hasChildren = true
  parent = "current_projects"
  identifier = "current_projects_softmatter"

  
[[main]]
  name = "Membrane Proteins Structure and Function"
  url = "project/biophysics/membrane_protein/"
#  url = "#projects_biophysics"
  weight = "1"
  parent = "current_projects_biophysics"
  
[[main]]
  name = "Functional and Mechanical Properties of Biological Soft Matter"
  url = "project/biophysics/bio_soft_matter/"
#  url = "#projects_biophysics"
  weight = "2"
  parent = "current_projects_biophysics"
  
[[main]]
  name = "Cell-Penetrating Peptides(CPPs) and Drug Delivery"
  url = "project/biophysics/cpp/"
#  url = "#projects_biophysics"
  weight = "3"
  parent = "current_projects_biophysics" 
  
[[main]]
  name = "Path Sampling of Rare Events"
  url = "project/biophysics/path_sampling/"
#  url = "#projects_biophysics"
  weight = "4"
  parent = "current_projects_biophysics" 

[[main]]
  name = "Theoretical Modeling of a Cell Division and the Min System"
  url = "project/biophysics/cell_division/"
#  url = "#projects_biophysics"
  weight = "5"
  parent = "current_projects_biophysics"
  

[[main]]
  name = "Self-Assembly of Polymers"
  url = "project/soft_matter_physics/self_assembly/"
#  url = "#projects_softmatter"
  weight = "1"
  parent = "current_projects_softmatter"


[[main]]
  name = "Polyelectrolyte-Polyampholyte Complexes"
  url = "project/soft_matter_physics/pe_pa/"
#  url = "#projects_softmatter"
  weight = "2"
  parent = "current_projects_softmatter"


[[main]]
  name = "Publications"
  url = "#featured"
  weight = 400
  
[[main]]
  name = "News"
  url = "#posts"
#  url = "#post2"
  weight = 500

[[main]]
  name = "Open Positions"
  url = "#positions"
  weight = 600
  
[[main]]
  name = "Contact"
  url = "#contact"
  weight = 700



# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
