[build]
command = "hugo --gc --minify -b $URL"
#  command = "hugo --gc --minify"
#command = "hugo"
  publish = "public"

[build.environment]
#  HUGO_VERSION = "0.66.0"
#  HUGO_VERSION = "0.108.0"
  HUGO_VERSION = "0.85.0"
  HUGO_ENABLEGITINFO = "false"
#  HUGO_ENABLEGITINFO = "true"
  
#[context.production.environment]
#  HUGO_VERSION = "0.108.0"
#  HUGO_ENV = "production"
#  HUGO_ENABLEGITINFO = "true"
 
#[context.split1]
# command = "hugo --gc --minify --enableGitInfo"

#[context.split1.environment]
#  HUGO_VERSION = "0.108.0"
#  HUGO_ENV = "production"

[context.deploy-preview]
 command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
# command = "hugo --gc --minify --enableGitInfo"

#[context.deploy-preview.environment]
#  HUGO_VERSION = "0.108.0"

#[context.branch-deploy]
#  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

#[context.branch-deploy.environment]
#  HUGO_VERSION = "0.108.0"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

